name = "MPFaPA"
author = "Facu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16931ea9e1a5e0d18443f9a90d08efbd0c74f8ca58d0a1ffaae2ee71a9cf3308"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
