name = "MPFaPA"
author = "Facu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c166eeb8010ee078db3b8cc7a1e2da795e695324420964625d64e6b8e6c5c25c"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
