name = "MPFaPA"
author = "Facu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0986c36d801a705f084369a610573afd79ebf9ac3eeefc1ee462e3f53c09cde7"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
